export const verificationRequests = [
  {
    id: "nadya-larasati",
    no: 1,
    name: "dr. Nadya Larasati",
    email: "nadya.larasati@email.com",
    identity: "STR67890123",
    specialization: "Dermatologi",
    document: "STR_Nadya.pdf",
    submittedAt: "20 May 2025",
    status: "Pending",
    phone: "+62 812-3456-7890",
    address: "Jakarta Selatan",
  },
  {
    id: "rafi-mahendra",
    no: 2,
    name: "dr. Rafi Mahendra",
    email: "rafi.mahendra@email.com",
    identity: "STR78901234",
    specialization: "Spesialis Kulit",
    document: "STR_Rafi.pdf",
    submittedAt: "19 May 2025",
    status: "Pending",
    phone: "+62 813-4567-8901",
    address: "Bandung",
  },
  {
    id: "lintang-ayu",
    no: 3,
    name: "dr. Lintang Ayu",
    email: "lintang.ayu@email.com",
    identity: "ID-DOC-89012345",
    specialization: "Kedokteran Estetika",
    document: "Identitas_Lintang.pdf",
    submittedAt: "18 May 2025",
    status: "Revision Required",
    phone: "+62 821-5678-9012",
    address: "Surabaya",
  },
  {
    id: "yoga-prasetyo",
    no: 4,
    name: "dr. Yoga Prasetyo",
    email: "yoga.prasetyo@email.com",
    identity: "STR90123456",
    specialization: "Dermatologi",
    document: "STR_Yoga.pdf",
    submittedAt: "17 May 2025",
    status: "Pending",
    phone: "+62 822-6789-0123",
    address: "Yogyakarta",
  },
  {
    id: "kirana-safitri",
    no: 5,
    name: "dr. Kirana Safitri",
    email: "kirana.safitri@email.com",
    identity: "STR01234567",
    specialization: "Spesialis Kulit",
    document: "STR_Kirana.pdf",
    submittedAt: "16 May 2025",
    status: "Revision Required",
    phone: "+62 823-7890-1234",
    address: "Semarang",
  },
];

export function getVerificationRequest(id: string) {
  return verificationRequests.find((request) => request.id === id);
}
